# Offense 
OFFENSE_NAME = 'offense'
OFFENSE_RANGE = 10
OFFENSE_DAMAGES = 15
OFFENSE_COST = 4

# Portail
PORTAIL_NAME = 'portail'
PORTAIL_RANGE = 4
PORTAIL_DAMAGES = 0
PORTAIL_COST = 1

# Mosure
MORSURE_NAME = 'morsure'
MORSURE_RANGE = 1
MORSURE_DAMAGES = 10
MORSURE_COST = 3 