# Ally :

P1_INIT_NAME = "Eliotrope"
P1_INIT_HP = 100
P1_INIT_PA = 5
P1_INIT_PM = 4
P1_INIT_POSITION_X = 15
P1_INIT_POSITION_Y = 24
P1_INIT_TEAM = "ally"

# Monster list

BOUFTOU_INIT_NAME = "Bouftou"
BOUFTOU_INIT_HP = 200
BOUFTOU_INIT_PA = 4
BOUFTOU_INIT_PM = 3
BOUFTOU_INIT_POSITION_X = 10
BOUFTOU_INIT_POSITION_Y = 0
BOUFTOU_INIT_TEAM = "ennemies"

TOFU_INIT_NAME = "Tofu"
TOFU_INIT_HP = 50
TOFU_INIT_PA = 8
TOFU_INIT_PM = 10
TOFU_INIT_POSITION_X = 5
TOFU_INIT_POSITION_Y = 0
TOFU_INIT_TEAM = "ennemies"


