# ALLY BOOST :

BUFF_DAMAGE_VALUE_NAME = 'buff-damage-value'
BUFF_DAMAGE_VALUE_DESC = 'All your spells gain 15 damages'
BUFF_DAMAGE_VALUE_VALUE = 15
BUFF_DAMAGE_VALUE_RATIO = 1
BUFF_DAMAGE_VALUE_ATTRIBUTION = 'ally'

BUFF_DAMAGE_RATIO_NAME = 'buff-damage-ratio'
BUFF_DAMAGE_RATIO_DESC = 'All your spells gain 50%% damage'
BUFF_DAMAGE_RATIO_VALUE = 0
BUFF_DAMAGE_RATIO_RATIO = 1.5
BUFF_DAMAGE_RATIO_ATTRIBUTION = 'ally'

BUFF_SPEED_VALUE_NAME = 'buff-speed-value'
BUFF_SPEED_VALUE_DESC = 'Allies gain 25 speed'
BUFF_SPEED_VALUE_VALUE = 25
BUFF_SPEED_VALUE_RATIO = 1
BUFF_SPEED_VALUE_ATTRIBUTION = 'ally'

BUFF_SPEED_RATIO_NAME = 'buff-speed-ratio'
BUFF_SPEED_RATIO_DESC = 'Allies gain 25 speed'
BUFF_SPEED_RATIO_VALUE = 25
BUFF_SPEED_RATIO_RATIO = 1
BUFF_SPEED_RATIO_ATTRIBUTION = 'ally'

BUFF_RANGE_NAME = 'buff-range'
BUFF_RANGE_DESC = 'All your spells gain 1 range'
BUFF_RANGE_VALUE = 1
BUFF_RANGE_VALUE_RATIO = 1
BUFF_RANGE_VALUE_ATTRIBUTION = 'ally'

