# Ally :

ARCHER_INIT_NAME = "Archer"
ARCHER_INIT_HP = 100
ARCHER_INIT_PA = 5
ARCHER_INIT_PM = 4
ARCHER_INIT_POSITION_X = 15
ARCHER_INIT_POSITION_Y = 24
ARCHER_INIT_TEAM = "ally"
ARCHER_INIT_PATHIMG = 'archer.png'

# Monster list

HAND_INIT_NAME = "hand"
HAND_INIT_HP = 200
HAND_INIT_PA = 4
HAND_INIT_PM = 3
HAND_INIT_POSITION_X = 10
HAND_INIT_POSITION_Y = 0
HAND_INIT_TEAM = 'ennemies'
HAND_INIT_PATHIMG = 'hand.png'

MOSKITOS_INIT_NAME = "moskitos"
MOSKITOS_INIT_HP = 50
MOSKITOS_INIT_PA = 8
MOSKITOS_INIT_PM = 10
MOSKITOS_INIT_POSITION_X = 5
MOSKITOS_INIT_POSITION_Y = 0
MOSKITOS_INIT_TEAM = 'ennemies'
MOSKITOS_INIT_PATHIMG = "moskitos.png"


